### ISSUE TITLE
add method "restart" to combine "stop" and "start"

### ISSUE THREAD

**Issue by kleinron** [jasonray/statman-stopwatch#56]
it would be nice to add a `restart` method to increase code readability, so that instead of explicitly calling `stop` and `start`, one could simply call `restart`.

**Comment by Jermy-Mouawad** [comment]
ERROR Error: Uncaught (in promise): TypeError: statman_stopwatch__WEBPACK_IMPORTED_MODULE_8__.Stopwatch is not a constructor.

**Comment by jasonray** [comment]
to be included in v2.15.2

**Comment by jasonray** [comment]
https://github.com/jasonray/statman-stopwatch/pull/83
