### ISSUE TITLE
Error in browser incorrect import of UUID V7

### ISSUE THREAD

**Issue by djaffer** [jasonray/statman-stopwatch#58]
The issue has been there for a while for using deprecated way of import. 

![statman-error](https://user-images.githubusercontent.com/5740725/118934540-13ef5780-b910-11eb-90a7-a7d013ec1536.gif)

**Comment by animald** [comment]
When will this be resolved?

**Comment by djaffer** [comment]
when will this be fixed?

**Comment by jasonray** [comment]
@djaffer , @animald : this should be resolved in [2.13](https://www.npmjs.com/package/statman-stopwatch/v/2.13.0)

**Comment by djaffer** [comment]
Thanks, @jasonray verified it's no longer throwing a warning.
